workspace(name = "inner")

load("//third_party:repos.bzl", "load_repos")
load_repos()

load("//third_party:repos_deps.bzl", "setup_repos_deps")
setup_repos_deps()

load("//third_party:repos_setup.bzl", "repos_setup")
repos_setup()
